apiVersion: v1
kind: Service
metadata:
  name: bl-db-operate-service
  namespace: operating
  labels:
    name: bl-db-operate
spec:
  type: LoadBalancer
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
  selector:
    role: mongo
