apiVersion: v1
kind: Service
metadata:
  name: bl-db-image-service
  namespace: index
  labels:
    name: bl-db-image
spec:
  type: LoadBalancer
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
  selector:
    role: mongo
